baseURL = "http://example.org/"
languageCode = 'en-us'
title = 'Sebastian'
theme = "gokarna"

enableRobotsTXT = true

[params]
  footer = "Sebastian"
  avatarURL = "/images/marcelino-avatar.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-m"

  socialIcons = [
    {name = "twitter", url = ""},
    {name = "linkedin", url = ""},
    {name = "github", url = ""},
    {name = "email", url = ""}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Resume"
    pre = "<span data-feather='user'></span>"
    url = "/about/resume"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/project"
    weight = 3

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 4